### ISSUE TITLE
Serialize fails when result is too long

### ISSUE THREAD

**Issue by luyuhuang** [hanxi/lua-seri#1]
When using luaL_Buffer, luaL_Buffer pushes variables to the stack when resizing. According to the Lua reference manual:

> During its normal operation, a string buffer uses a variable number of stack slots. So, while using a buffer, **you cannot assume that you know where the top of the stack is**.

So, in function `append_table`, if luaL_Buffer resized when appending table keys or values, It'll push variables to the stack, causing the stack to be incorrect when call `lua_pop` at the end of the cycle.  This often leads to segmentation fault.

In my environment, if the length of result is greater then 8192, it'll lead to segmentation fault. Because my `LUAL_BUFFERSIZE` is 8192.

**Comment by hanxi** [comment]
thank you, so need use another buffer replace luaL_Buffer. I saw you already implement it.

**Comment by luyuhuang** [comment]
Thanks for your star. BTW, I don't really like copy it again. Would you have any better ideas about it?

**Comment by hanxi** [comment]
Another solution,  I think can use a table cache all strings, like in pure lua.

**Comment by luyuhuang** [comment]
Well, this cannot avoid double copy(from object to cache, then from cache to luaL_Buffer). I mean can we have any way to copy directly from the object to luaL_Buffer while keeping the stack correct 😂?

**Comment by hanxi** [comment]
Fix https://github.com/hanxi/lua-seri/commit/933ceeb13179ccecb03d536d6c6ac0afd0ef2e4d
